[phases.setup]
nixPkgs = ["...", "php82"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-scripts",
    "npm ci"
]

[phases.build]
cmds = [
    "mkdir -p storage/logs storage/framework/cache storage/framework/sessions storage/framework/views storage/app/public/profile-photos bootstrap/cache",
    "chmod -R 755 storage bootstrap/cache",
    "npm run build",
    "php artisan storage:link || true",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"